version: '3'
services:
 mongodb:
  image: mongo:latest  
  container_name: mongodb2
  ports:
   - 27017:27017
  volumes:
   - /var/lib/data

 main:
  image: fruit-shop-final
  container_name: fruit-shopv2c
  stdin_open: true  
  tty: true   #docker run -it
  ports:
   - 8080:8080
  environment:
   - MONGO_HOST= mongodb:27017
  links: 
   - mongodb
  